# Generated by Django 2.2.7 on 2019-11-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('min_number', models.IntegerField()),
                ('max_number', models.IntegerField()),
                ('capasity', models.IntegerField()),
                ('operator', models.TextField()),
                ('region', models.TextField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='phonenumber',
            constraint=models.UniqueConstraint(fields=('code', 'min_number', 'max_number'), name='phone_number'),
        ),
    ]
