# Generated by Django 2.2.7 on 2019-11-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numbers_app', '0002_auto_20191109_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneNumber',
            new_name='RegistryEntry',
        ),
    ]
